table:
  name: community_settings
  schema: public
object_relationships:
  - name: community
    using:
      foreign_key_constraint_on: community_id
select_permissions:
  - role: user
    permission:
      columns:
        - community_id
        - id
        - name
        - settings
        - version
      filter:
        community:
          community_users:
            user_id:
              _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - name
        - settings
        - version
      filter:
        community:
          community_users:
            user_id:
              _eq: X-Hasura-User-Id
      check: null
