table:
  name: chatbot_settings
  schema: public
object_relationships:
  - name: chatbot
    using:
      foreign_key_constraint_on: chatbot_id
insert_permissions:
  - role: user
    permission:
      check:
        chatbot:
          community:
            community_users:
              user_id:
                _eq: X-Hasura-User-Id
      columns:
        - chatbot_id
        - id
        - settings
        - channel
        - created_at
        - updated_at
select_permissions:
  - role: user
    permission:
      columns:
        - chatbot_id
        - id
        - settings
        - channel
        - created_at
        - updated_at
      filter:
        chatbot:
          community:
            community_users:
              user_id:
                _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - chatbot_id
        - id
        - settings
        - channel
        - created_at
        - updated_at
      filter:
        chatbot:
          community:
            community_users:
              user_id:
                _eq: X-Hasura-User-Id
      check: null
