-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."dns_hosted_zones" add column "is_external_domain" boolean
--  not null default 'false';
